{
  "timelineObjects": [{
    "activitySegment": {
      "startLocation": {
        "latitudeE7": 412096065,
        "longitudeE7": -760160470,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "endLocation": {
        "latitudeE7": 412117388,
        "longitudeE7": -758987635,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "duration": {
        "startTimestamp": "2022-05-01T17:02:26.914Z",
        "endTimestamp": "2022-05-01T17:12:57.488Z"
      },
      "distance": 10726,
      "activityType": "IN_PASSENGER_VEHICLE",
      "confidence": "HIGH",
      "activities": [{
        "activityType": "IN_PASSENGER_VEHICLE",
        "probability": 98.10378551483154
      }, {
        "activityType": "STILL",
        "probability": 0.7128706201910973
      }, {
        "activityType": "WALKING",
        "probability": 0.5713927559554577
      }, {
        "activityType": "MOTORCYCLING",
        "probability": 0.41432459838688374
      }, {
        "activityType": "CYCLING",
        "probability": 0.09333178168162704
      }, {
        "activityType": "IN_BUS",
        "probability": 0.03288815205451101
      }, {
        "activityType": "RUNNING",
        "probability": 0.025898785679601133
      }, {
        "activityType": "IN_FERRY",
        "probability": 0.02408062864560634
      }, {
        "activityType": "FLYING",
        "probability": 0.010380263847764581
      }, {
        "activityType": "SKIING",
        "probability": 0.005930863335379399
      }, {
        "activityType": "IN_TRAIN",
        "probability": 0.0026661495212465525
      }, {
        "activityType": "SAILING",
        "probability": 0.0018598890164867043
      }, {
        "activityType": "IN_SUBWAY",
        "probability": 5.543173756450415E-4
      }, {
        "activityType": "IN_TRAM",
        "probability": 3.648080451057467E-5
      }, {
        "activityType": "IN_VEHICLE",
        "probability": 3.384838798137224E-8
      }],
      "waypointPath": {
        "waypoints": [{
          "latE7": 412096099,
          "lngE7": -760160369
        }, {
          "latE7": 412081871,
          "lngE7": -759860992
        }, {
          "latE7": 412117347,
          "lngE7": -758987503
        }],
        "source": "INFERRED",
        "roadSegment": [{
          "placeId": "ChIJD0qnLJMNxYkRwo0eRB765-4",
          "duration": "2s"
        }, {
          "placeId": "ChIJr3BxVekNxYkR2_MxfQzkBug",
          "duration": "7s"
        }, {
          "placeId": "ChIJR8sj1O4NxYkR4-shCYmV9Z0",
          "duration": "30s"
        }, {
          "placeId": "ChIJr9oxYe8NxYkRAPlQvvqA4i8",
          "duration": "10s"
        }, {
          "placeId": "ChIJI6PfjuUNxYkRmCjgtpYSqRs",
          "duration": "2s"
        }, {
          "placeId": "ChIJq8TxkeUNxYkRj7Medy2oj_s",
          "duration": "2s"
        }, {
          "placeId": "ChIJV46eleUNxYkRTKCMUVovmXM",
          "duration": "5s"
        }, {
          "placeId": "ChIJ0QjnxuUNxYkRjGqhXpbR9w0",
          "duration": "7s"
        }, {
          "placeId": "ChIJfzzg0OUNxYkRWZEBhRho7u8",
          "duration": "12s"
        }, {
          "placeId": "ChIJPY8H1uUNxYkRUWXvuA0X2ZE",
          "duration": "3s"
        }, {
          "placeId": "ChIJg5vt1eUNxYkRw1gL4wuJc9s",
          "duration": "0s"
        }, {
          "placeId": "ChIJmXX9I-QNxYkR50I-BtH4F78",
          "duration": "15s"
        }, {
          "placeId": "ChIJ0WpbCOQNxYkR4r_z_pTJqY8",
          "duration": "3s"
        }, {
          "placeId": "ChIJOar_7eMNxYkRiFffs-TSDCk",
          "duration": "5s"
        }, {
          "placeId": "ChIJURUPweMNxYkRe3viPaiT_-I",
          "duration": "5s"
        }, {
          "placeId": "ChIJIR9oyeMNxYkR7IZiEcFz4XU",
          "duration": "4s"
        }, {
          "placeId": "ChIJ08GYOeINxYkR1l3RzCdS3GM",
          "duration": "2s"
        }, {
          "placeId": "ChIJ08GYOeINxYkRgSf0e-0CjP0",
          "duration": "12s"
        }, {
          "placeId": "ChIJGXUibeINxYkRLh8FgZubHW4",
          "duration": "3s"
        }, {
          "placeId": "ChIJE0xG0AkOxYkRVgGM6K1GcuA",
          "duration": "2s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkRkNxcop9FuuM",
          "duration": "2s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkR0VS2zl6uWjU",
          "duration": "9s"
        }, {
          "placeId": "ChIJif40-AgOxYkRlZWmsGQqgrE",
          "duration": "12s"
        }, {
          "placeId": "ChIJUSxGuAgOxYkRXtBus6_kOw4",
          "duration": "5s"
        }, {
          "placeId": "ChIJt5yiTQ8OxYkRPrsi0Dx0h7U",
          "duration": "1s"
        }, {
          "placeId": "ChIJhQ5dUA8OxYkRu6YjZCrrwb4",
          "duration": "1s"
        }, {
          "placeId": "ChIJ9SEHWw8OxYkRt0BL7dbctV8",
          "duration": "0s"
        }, {
          "placeId": "ChIJeUOWfA8OxYkRk-_efkESy-A",
          "duration": "1s"
        }, {
          "placeId": "ChIJeUOWfA8OxYkRzJSAEmVcK84",
          "duration": "7s"
        }, {
          "placeId": "ChIJ_52lAxEOxYkRqXm17zCxQtU",
          "duration": "1s"
        }, {
          "placeId": "ChIJ0ebRED4OxYkR3Zxpfvyfq-E",
          "duration": "1s"
        }, {
          "placeId": "ChIJf-C4aT4OxYkRSETaUPpYIUE",
          "duration": "3s"
        }, {
          "placeId": "ChIJ3bwl8j4OxYkRNwBhGgk_d38",
          "duration": "5s"
        }, {
          "placeId": "ChIJW9BT6T4OxYkRRnpkw4JEqsc",
          "duration": "1s"
        }, {
          "placeId": "ChIJOX1kJzoOxYkRf5VcklPnKuk",
          "duration": "29s"
        }, {
          "placeId": "ChIJAcMNDDEOxYkRGLUljJGDppw",
          "duration": "3s"
        }, {
          "placeId": "ChIJpzaRhjEOxYkRHaKhWup2KdU",
          "duration": "3s"
        }, {
          "placeId": "ChIJBXTXgc0PxYkRxwROnduVTtw",
          "duration": "3s"
        }, {
          "placeId": "ChIJBXTXgc0PxYkRaC57tTeyKVQ",
          "duration": "6s"
        }, {
          "placeId": "ChIJw_E0LMMPxYkRYjc7ENLLQm4",
          "duration": "6s"
        }, {
          "placeId": "ChIJTZaqyMIPxYkR5n44QpCiT8w",
          "duration": "0s"
        }, {
          "placeId": "ChIJj2r2ROgPxYkRwB-RErYNFeE",
          "duration": "3s"
        }, {
          "placeId": "ChIJj2r2ROgPxYkR3KcdK56HhGw",
          "duration": "4s"
        }, {
          "placeId": "ChIJB72HROgPxYkR3pUnjj2RtTE",
          "duration": "2s"
        }, {
          "placeId": "ChIJRzxOiOgPxYkRJaOyUAHEP8g",
          "duration": "4s"
        }, {
          "placeId": "ChIJRzxOiOgPxYkRXwks3J8JKXg",
          "duration": "0s"
        }, {
          "placeId": "ChIJ41O1negPxYkRi-YEGzrDeE8",
          "duration": "6s"
        }, {
          "placeId": "ChIJP1ZOIOYPxYkRuIvoI5GcVik",
          "duration": "0s"
        }, {
          "placeId": "ChIJ9SphH-YPxYkRJuUywYC7pak",
          "duration": "0s"
        }, {
          "placeId": "ChIJu44YH-YPxYkRdwCkMzIlqp8",
          "duration": "0s"
        }, {
          "placeId": "ChIJDz4_GeYPxYkRUqE4Y1--jR8",
          "duration": "1s"
        }, {
          "placeId": "ChIJX1_NG-YPxYkRkLO50SF0nqo",
          "duration": "0s"
        }, {
          "placeId": "ChIJ_SR6CeYPxYkR4kfK2Zy2W8A",
          "duration": "10s"
        }, {
          "placeId": "ChIJ9zQOxOUPxYkRfq5kCW0JoeU",
          "duration": "4s"
        }, {
          "placeId": "ChIJtUE7_-QPxYkRjmrVr9z4xN4",
          "duration": "14s"
        }, {
          "placeId": "ChIJI4vCrOQPxYkRbaaoyrB7pP0",
          "duration": "13s"
        }, {
          "placeId": "ChIJTc9zvfwPxYkRoy5F7YODmAU",
          "duration": "3s"
        }, {
          "placeId": "ChIJa48w7fwPxYkR2BMfpJh1PAo",
          "duration": "4s"
        }, {
          "placeId": "ChIJ407Y9vwPxYkRBCRT0CtyF-o",
          "duration": "1s"
        }, {
          "placeId": "ChIJf2GhU_wPxYkRbwv0QHVxzns",
          "duration": "7s"
        }, {
          "placeId": "ChIJ0VjCx_0PxYkRpALr_fF_YdM",
          "duration": "6s"
        }, {
          "placeId": "ChIJ3RSe5_0PxYkRTGx9a44HkBA",
          "duration": "4s"
        }, {
          "placeId": "ChIJ41WJ4v0PxYkRPRSLOyOs8RA",
          "duration": "1s"
        }, {
          "placeId": "ChIJ1bvwBv4PxYkRibSowP3wy9E",
          "duration": "1s"
        }, {
          "placeId": "ChIJzyRN_QEQxYkRJPWJMPB6ZgU",
          "duration": "5s"
        }, {
          "placeId": "ChIJefkW6AEQxYkRkcEs8ibqUM0",
          "duration": "4s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRKqqacfbA6Uc",
          "duration": "8s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRYqS4-na-zBM",
          "duration": "5s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkRWclki4fv0Wg",
          "duration": "1s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkROjjV5Qnr3tM",
          "duration": "6s"
        }, {
          "placeId": "ChIJQ2wclQAQxYkR0M-b3liYOwQ",
          "duration": "0s"
        }, {
          "placeId": "ChIJVyESvgAQxYkRITvYT4Uw8qg",
          "duration": "3s"
        }, {
          "placeId": "ChIJGaZquwAQxYkRAPL00k-vffA",
          "duration": "5s"
        }, {
          "placeId": "ChIJ63u1nwAQxYkRpkYvMcKfaZU",
          "duration": "19s"
        }, {
          "placeId": "ChIJVYsde6oaxYkRV9LeTwnol58",
          "duration": "3s"
        }, {
          "placeId": "ChIJi7lkbqoaxYkRWDbhAlkqTyM",
          "duration": "9s"
        }, {
          "placeId": "ChIJB3XYKaoaxYkR-1tMR7kSNiU",
          "duration": "7s"
        }],
        "distanceMeters": 11510.987838921475,
        "travelMode": "DRIVE",
        "confidence": 0.9998740109259133
      },
      "parkingEvent": {
        "location": {
          "latitudeE7": 412130135,
          "longitudeE7": -758980147,
          "accuracyMetres": 82
        },
        "method": "END_OF_ACTIVITY_SEGMENT",
        "locationSource": "NOT_FROM_RAW_LOCATION",
        "timestamp": "2022-05-01T17:14:54.493Z"
      }
    }
  }, {
    "placeVisit": {
      "location": {
        "latitudeE7": 412112007,
        "longitudeE7": -758984985,
        "placeId": "ChIJB4B_VTEbxYkRlrZWUAj6vtg",
        "address": "Hazleton St, Ashley, PA 18706, USA",
        "name": "Ashley Trailer Park",
        "sourceInfo": {
          "deviceTag": -1449989162
        },
        "locationConfidence": 81.999596,
        "calibratedProbability": 73.88591
      },
      "duration": {
        "startTimestamp": "2022-05-01T17:12:57.488Z",
        "endTimestamp": "2022-05-01T17:22:29.936Z"
      },
      "placeConfidence": "MEDIUM_CONFIDENCE",
      "centerLatE7": 412131725,
      "centerLngE7": -758981800,
      "visitConfidence": 95,
      "otherCandidateLocations": [{
        "latitudeE7": 412128970,
        "longitudeE7": -758979000,
        "placeId": "ChIJy1E9j6kaxYkRJTNBNWpOg9U",
        "address": "86 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 3.3776038,
        "calibratedProbability": 3.0433972
      }, {
        "latitudeE7": 412128943,
        "longitudeE7": -758978353,
        "placeId": "ChIJ9ZEkc6kaxYkRJydgLHIpVNg",
        "address": "67 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 3.0984933,
        "calibratedProbability": 2.791904
      }, {
        "latitudeE7": 412121196,
        "longitudeE7": -759001558,
        "placeId": "ChIJBUMUpgAQxYkRf4cYPsxGcDE",
        "address": "1 Hazleton St, Ashley, PA 18706, USA",
        "name": "Ashley Municipal Park",
        "locationConfidence": 1.8251643,
        "calibratedProbability": 1.6445682
      }, {
        "latitudeE7": 412127898,
        "longitudeE7": -758979345,
        "placeId": "ChIJ4xM6iakaxYkRQdCa2g9YpCU",
        "address": "61 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 1.7196921,
        "calibratedProbability": 1.5495323
      }, {
        "latitudeE7": 412115157,
        "longitudeE7": -759015916,
        "placeId": "ChIJ6e156wAQxYkRXGkL2RgbhZs",
        "address": "43 S Main St, Ashley, PA 18706, USA",
        "name": "Family Dollar",
        "locationConfidence": 1.6818289,
        "calibratedProbability": 1.5154154
      }, {
        "latitudeE7": 412129741,
        "longitudeE7": -758977438,
        "placeId": "ChIJi7-cj6kaxYkRty7fSoPz_hk",
        "address": "87 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 1.2543269,
        "calibratedProbability": 1.130214
      }, {
        "latitudeE7": 412145068,
        "longitudeE7": -758994817,
        "placeId": "ChIJJXFaFSAbxYkRZ01zIyl39wc",
        "address": "23 N Main St, Ashley, PA 18706, USA",
        "name": "The Grand Bank",
        "locationConfidence": 0.8742172,
        "calibratedProbability": 0.78771526
      }, {
        "latitudeE7": 412139010,
        "longitudeE7": -758998260,
        "placeId": "ChIJn6d14akaxYkRHLRmDMln3ro",
        "address": "1 N Main St, Ashley, PA 18706, USA",
        "name": "Kelsey�u0027s",
        "locationConfidence": 0.7787029,
        "calibratedProbability": 0.70165193
      }, {
        "latitudeE7": 412141217,
        "longitudeE7": -758989490,
        "placeId": "ChIJX-hV56kaxYkRoT1mtv0WhT0",
        "address": "49 W Cemetery St, Ashley, PA 18706, USA",
        "name": "Ashley Fire Department",
        "locationConfidence": 0.5861724,
        "calibratedProbability": 0.5281719
      }],
      "editConfirmationStatus": "NOT_CONFIRMED",
      "locationConfidence": 67,
      "placeVisitType": "SINGLE_PLACE",
      "placeVisitImportance": "MAIN"
    }
  }, {
    "activitySegment": {
      "startLocation": {
        "latitudeE7": 412126843,
        "longitudeE7": -758983478,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "endLocation": {
        "latitudeE7": 412106958,
        "longitudeE7": -760169276,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "duration": {
        "startTimestamp": "2022-05-01T17:22:29.936Z",
        "endTimestamp": "2022-05-01T17:48:05.916Z"
      },
      "distance": 21698,
      "activityType": "IN_PASSENGER_VEHICLE",
      "confidence": "HIGH",
      "activities": [{
        "activityType": "IN_PASSENGER_VEHICLE",
        "probability": 93.14832091331482
      }, {
        "activityType": "STILL",
        "probability": 5.8015573769807816
      }, {
        "activityType": "WALKING",
        "probability": 0.5502994637936354
      }, {
        "activityType": "MOTORCYCLING",
        "probability": 0.2546085976064205
      }, {
        "activityType": "CYCLING",
        "probability": 0.08200747543014586
      }, {
        "activityType": "IN_BUS",
        "probability": 0.05061060073785484
      }, {
        "activityType": "IN_FERRY",
        "probability": 0.03415205283090472
      }, {
        "activityType": "FLYING",
        "probability": 0.03396823303773999
      }, {
        "activityType": "RUNNING",
        "probability": 0.02870559983421117
      }, {
        "activityType": "SKIING",
        "probability": 0.007627121522091329
      }, {
        "activityType": "IN_TRAIN",
        "probability": 0.004515947148320265
      }, {
        "activityType": "SAILING",
        "probability": 0.002874255551432725
      }, {
        "activityType": "IN_SUBWAY",
        "probability": 6.354548077069921E-4
      }, {
        "activityType": "IN_TRAM",
        "probability": 1.1489413509480073E-4
      }, {
        "activityType": "IN_VEHICLE",
        "probability": 6.317069645156437E-8
      }],
      "waypointPath": {
        "waypoints": [{
          "latE7": 412126693,
          "lngE7": -758983154
        }, {
          "latE7": 412183761,
          "lngE7": -758853607
        }, {
          "latE7": 412358169,
          "lngE7": -758493957
        }, {
          "latE7": 412082901,
          "lngE7": -759860458
        }, {
          "latE7": 412107276,
          "lngE7": -760168228
        }],
        "source": "INFERRED",
        "roadSegment": [{
          "placeId": "ChIJB3XYKaoaxYkR-ltMR7kSNiU",
          "duration": "33s"
        }, {
          "placeId": "ChIJi7lkbqoaxYkRWTbhAlkqTyM",
          "duration": "15s"
        }, {
          "placeId": "ChIJVYsde6oaxYkRVtLeTwnol58",
          "duration": "6s"
        }, {
          "placeId": "ChIJ0b62Y6oaxYkRughwbz3jgI0",
          "duration": "9s"
        }, {
          "placeId": "ChIJuQiJWKoaxYkRWmhxeIAY2dg",
          "duration": "6s"
        }, {
          "placeId": "ChIJC-ZPVKoaxYkRAtGLGmtVt8I",
          "duration": "1s"
        }, {
          "placeId": "ChIJC-ZPVKoaxYkRcQto0llXUYc",
          "duration": "1s"
        }, {
          "placeId": "ChIJi4c2CqwaxYkRx64BYsFopow",
          "duration": "50s"
        }, {
          "placeId": "ChIJxeVy060axYkRCxJOrfE-kAM",
          "duration": "12s"
        }, {
          "placeId": "ChIJi6jqca4axYkRiNkFAIirTgE",
          "duration": "15s"
        }, {
          "placeId": "ChIJUefYL64axYkRxIkcOAmuIT4",
          "duration": "4s"
        }, {
          "placeId": "ChIJWcYR1K8axYkRsfpIE2C1h_A",
          "duration": "1s"
        }, {
          "placeId": "ChIJWcYR1K8axYkR1qwz4YwV-eI",
          "duration": "2s"
        }, {
          "placeId": "ChIJy7L4ILAaxYkRFnXMPIBqx10",
          "duration": "3s"
        }, {
          "placeId": "ChIJlYtXBbAaxYkRthrhmRGJIw4",
          "duration": "4s"
        }, {
          "placeId": "ChIJB54lmLoaxYkRpS1lWSlv5QE",
          "duration": "8s"
        }, {
          "placeId": "ChIJHXb58LoaxYkR1Ztwx43qTh8",
          "duration": "2s"
        }, {
          "placeId": "ChIJHXb58LoaxYkRzgis_RAcfDg",
          "duration": "1s"
        }, {
          "placeId": "ChIJP2nVq7saxYkR_ClQVBrskdM",
          "duration": "4s"
        }, {
          "placeId": "ChIJnT3EqLsaxYkRw3lcFe6fq3E",
          "duration": "1s"
        }, {
          "placeId": "ChIJZcnFpbsaxYkRL_q7qXKSEpk",
          "duration": "1s"
        }, {
          "placeId": "ChIJPQFhmLsaxYkRCAgwovIQnBU",
          "duration": "7s"
        }, {
          "placeId": "ChIJcUKPi7saxYkRfEZTekiTILQ",
          "duration": "8s"
        }, {
          "placeId": "ChIJ-yfjDLwaxYkRRQTX0CVEXds",
          "duration": "6s"
        }, {
          "placeId": "ChIJ-yfjDLwaxYkRVpwj7bTWomA",
          "duration": "7s"
        }, {
          "placeId": "ChIJv3TsE7waxYkRm5us2dhVZJo",
          "duration": "3s"
        }, {
          "placeId": "ChIJ35w_PbwaxYkRSh83CMzQfYs",
          "duration": "4s"
        }, {
          "placeId": "ChIJRV3_JLwaxYkRplp1kkaxuKY",
          "duration": "3s"
        }, {
          "placeId": "ChIJRV3_JLwaxYkRUN4cKyVtVdA",
          "duration": "1s"
        }, {
          "placeId": "ChIJpy4HKbwaxYkRPr6fQF-Gz8Y",
          "duration": "4s"
        }, {
          "placeId": "ChIJr-BdgL4axYkRUA0Ld-KmlRo",
          "duration": "3s"
        }, {
          "placeId": "ChIJ-3qrfL4axYkREn9mE-PVI78",
          "duration": "6s"
        }, {
          "placeId": "ChIJs008Zr4axYkRsJOLfSZbfIA",
          "duration": "1s"
        }, {
          "placeId": "ChIJh3pxaL4axYkRDDl8xIXrZWo",
          "duration": "0s"
        }, {
          "placeId": "ChIJB2W8Rr4axYkRTve67rTafW8",
          "duration": "4s"
        }, {
          "placeId": "ChIJ3bzaR74axYkRY2Z_xEVprBg",
          "duration": "1s"
        }, {
          "placeId": "ChIJ93wuNr4axYkRWY6ug0ms4Hs",
          "duration": "2s"
        }, {
          "placeId": "ChIJ9-JaNL4axYkRj2TclG1WUbY",
          "duration": "2s"
        }, {
          "placeId": "ChIJc5q-zL8axYkREVLcb-wCenQ",
          "duration": "2s"
        }, {
          "placeId": "ChIJ827Pzb8axYkR_XF3cSbQb3Y",
          "duration": "1s"
        }, {
          "placeId": "ChIJW7ot0L8axYkRJc_XnPYIsDE",
          "duration": "2s"
        }, {
          "placeId": "ChIJyzRZ2b8axYkRBarme594Wjg",
          "duration": "6s"
        }, {
          "placeId": "ChIJo9Lq378axYkR0THI7dLp8mU",
          "duration": "0s"
        }, {
          "placeId": "ChIJVRmmX5UaxYkRC10zuZJjNkc",
          "duration": "4s"
        }, {
          "placeId": "ChIJJ0XEW5UaxYkRBqNNq2_kfeY",
          "duration": "3s"
        }, {
          "placeId": "ChIJ9-igWpUaxYkRUD33IdhfaLk",
          "duration": "2s"
        }, {
          "placeId": "ChIJ-WxK3-oaxYkRk6E9hlYiwic",
          "duration": "32s"
        }, {
          "placeId": "ChIJLeQ6dusaxYkRa9KjpjnvTtk",
          "duration": "1s"
        }, {
          "placeId": "ChIJgUggg-saxYkR5XxZwTbn63Q",
          "duration": "2s"
        }, {
          "placeId": "ChIJqeMBeOwaxYkREc-gKo4n9SY",
          "duration": "3s"
        }, {
          "placeId": "ChIJqeMBeOwaxYkR-RNsHbHY6Os",
          "duration": "3s"
        }, {
          "placeId": "ChIJZd20JewaxYkRuK3oCWAPeNc",
          "duration": "20s"
        }, {
          "placeId": "ChIJPZqkae4axYkRKzzQfzlsyIY",
          "duration": "7s"
        }, {
          "placeId": "ChIJd0PbOe4axYkRU9zjpFtJnHc",
          "duration": "4s"
        }, {
          "placeId": "ChIJh7io1u8axYkR1nLVQ6OEy8M",
          "duration": "15s"
        }, {
          "placeId": "ChIJh7io1u8axYkRJTQqxTiNF7U",
          "duration": "2s"
        }, {
          "placeId": "ChIJk1UsIvAaxYkR2DtGwr2WNFA",
          "duration": "3s"
        }, {
          "placeId": "ChIJxfjTGfAaxYkReCZbVn3YzRk",
          "duration": "9s"
        }, {
          "placeId": "ChIJX87IDPAaxYkRmlbVmf5IF34",
          "duration": "19s"
        }, {
          "placeId": "ChIJLc_KnPoaxYkRaH8OLcuUvmg",
          "duration": "12s"
        }, {
          "placeId": "ChIJdVsVYvoaxYkRer7rFqbW9KE",
          "duration": "6s"
        }, {
          "placeId": "ChIJQfbd9PoaxYkRbAMwiyXrV5w",
          "duration": "2s"
        }, {
          "placeId": "ChIJQfbd9PoaxYkRR96lBlv5p1Q",
          "duration": "7s"
        }, {
          "placeId": "ChIJkxkL-voaxYkRtdDlyKM03bk",
          "duration": "7s"
        }, {
          "placeId": "ChIJmdUCA_saxYkRpYJJTJHhXx8",
          "duration": "10s"
        }, {
          "placeId": "ChIJTTRWDPsaxYkRixl-WQQSwhI",
          "duration": "7s"
        }, {
          "placeId": "ChIJZ0hxd_saxYkR1x8GFstyEJ8",
          "duration": "8s"
        }, {
          "placeId": "ChIJlZh4evwaxYkR2n_LuM-0ulM",
          "duration": "21s"
        }, {
          "placeId": "ChIJZ7HIPvwaxYkRU4E6NNK7oxU",
          "duration": "3s"
        }, {
          "placeId": "ChIJZ7HIPvwaxYkRsa-h7ajopt8",
          "duration": "7s"
        }, {
          "placeId": "ChIJ59SLLvwaxYkR6v3IEDWnH3s",
          "duration": "7s"
        }, {
          "placeId": "ChIJ59SLLvwaxYkRuzgenkhPdyY",
          "duration": "3s"
        }, {
          "placeId": "ChIJ45Lc1f0axYkRFWYompybeK8",
          "duration": "26s"
        }, {
          "placeId": "ChIJ0bjqFv4axYkRIOZyhjq3A54",
          "duration": "1s"
        }, {
          "placeId": "ChIJ3_mTF_4axYkRzKEntrhOlyA",
          "duration": "2s"
        }, {
          "placeId": "ChIJ-4odIv4axYkRnowuIvrpNHk",
          "duration": "7s"
        }, {
          "placeId": "ChIJ6bV07AEbxYkRFbMYNRSGP6A",
          "duration": "28s"
        }, {
          "placeId": "ChIJLWAbRgIbxYkRMQyBmJ28LgU",
          "duration": "33s"
        }, {
          "placeId": "ChIJg0zEzPwaxYkRgY-0qz7aZpM",
          "duration": "2s"
        }, {
          "placeId": "ChIJIxoRWOMaxYkRMseOSJ245Ro",
          "duration": "1s"
        }, {
          "placeId": "ChIJj570uusaxYkR0xZhF6aUJu8",
          "duration": "2s"
        }, {
          "placeId": "ChIJHxZZ_bsaxYkRXWhBtNMR3Ns",
          "duration": "1s"
        }, {
          "placeId": "ChIJzRkH47saxYkRngN4eFz0EMM",
          "duration": "1s"
        }, {
          "placeId": "ChIJ-VFJAbAaxYkR-d5-6w83GTg",
          "duration": "1s"
        }, {
          "placeId": "ChIJNSNy3asaxYkRQwr7JX7IHPI",
          "duration": "3s"
        }, {
          "placeId": "ChIJvTUNC_8PxYkRWNjvG04N3Ak",
          "duration": "2s"
        }, {
          "placeId": "ChIJ904R-_sPxYkROjSVxwzm3p0",
          "duration": "2s"
        }, {
          "placeId": "ChIJdebd6_sPxYkRBQk-IBdPhn4",
          "duration": "4s"
        }, {
          "placeId": "ChIJ4cfn1voPxYkRRnJZMwXife0",
          "duration": "9s"
        }, {
          "placeId": "ChIJfd2YO-UPxYkRGPMghC8sde4",
          "duration": "2s"
        }, {
          "placeId": "ChIJ49DJcuUPxYkR-VwChG4XbaY",
          "duration": "0s"
        }, {
          "placeId": "ChIJSdCwdeUPxYkRS3csD3zBA4g",
          "duration": "9s"
        }, {
          "placeId": "ChIJCzXVj-UPxYkRSNgwgNjmO_o",
          "duration": "2s"
        }, {
          "placeId": "ChIJgTe4q-gPxYkRIPF6blesLMk",
          "duration": "2s"
        }, {
          "placeId": "ChIJQeCtpegPxYkROKZgjlBESpA",
          "duration": "6s"
        }, {
          "placeId": "ChIJQeCtpegPxYkRF_oMydoHm8c",
          "duration": "3s"
        }, {
          "placeId": "ChIJO1pQt8IPxYkRpdzI3YbJESc",
          "duration": "1s"
        }, {
          "placeId": "ChIJkab6zsIPxYkRNXz96xZxzcY",
          "duration": "3s"
        }, {
          "placeId": "ChIJx9B9LMMPxYkRQN7IlTe8Vgg",
          "duration": "3s"
        }, {
          "placeId": "ChIJx9B9LMMPxYkR3O_EPcfaiZs",
          "duration": "3s"
        }, {
          "placeId": "ChIJ8QtmgM0PxYkRZgDF6iZCHG4",
          "duration": "3s"
        }, {
          "placeId": "ChIJGcMYgM0PxYkRroCvZNsZYyU",
          "duration": "1s"
        }, {
          "placeId": "ChIJGcMYgM0PxYkR4Qqsicbw5IM",
          "duration": "9s"
        }, {
          "placeId": "ChIJwUfEPTIOxYkRUkuChCArEtM",
          "duration": "2s"
        }, {
          "placeId": "ChIJOyamnDEOxYkRuUPgF0PVGRM",
          "duration": "12s"
        }, {
          "placeId": "ChIJOyamnDEOxYkR7fKr8ri1CmE",
          "duration": "2s"
        }, {
          "placeId": "ChIJlTcaBDoOxYkRFb2LAB8AFWI",
          "duration": "4s"
        }, {
          "placeId": "ChIJvWAHHjoOxYkRJsJDsJwmCLc",
          "duration": "13s"
        }, {
          "placeId": "ChIJvWAHHjoOxYkRvnDC3akm-Yg",
          "duration": "6s"
        }, {
          "placeId": "ChIJWYUSODkOxYkRO6N5kqHmwMg",
          "duration": "10s"
        }, {
          "placeId": "ChIJWYUSODkOxYkR5owZh_xhcDI",
          "duration": "7s"
        }, {
          "placeId": "ChIJZyxl7D4OxYkRfAhSRROU7nc",
          "duration": "2s"
        }, {
          "placeId": "ChIJLZlAaT4OxYkR89FFc05HI_A",
          "duration": "12s"
        }, {
          "placeId": "ChIJQ9opNxEOxYkRPVPRd9mUgQE",
          "duration": "2s"
        }, {
          "placeId": "ChIJ8-Gz8hAOxYkRlGndomOBgi0",
          "duration": "25s"
        }, {
          "placeId": "ChIJz1g2ihoOxYkREExuMpsF8yM",
          "duration": "12s"
        }, {
          "placeId": "ChIJ5Zar9RoOxYkRLTaHv2AVEJk",
          "duration": "1s"
        }, {
          "placeId": "ChIJIaCH9BoOxYkRJwcKgFcKOc4",
          "duration": "1s"
        }, {
          "placeId": "ChIJjfBB7RoOxYkRu1OXXozNuVY",
          "duration": "3s"
        }, {
          "placeId": "ChIJhwcKuRoOxYkRO6S7HsLqQOU",
          "duration": "9s"
        }, {
          "placeId": "ChIJhwcKuRoOxYkRDhe_JPgFVxc",
          "duration": "1s"
        }, {
          "placeId": "ChIJfRkyRQUOxYkR4Nmaxpbz5IY",
          "duration": "8s"
        }, {
          "placeId": "ChIJd6_sZAUOxYkRAiDsN0pRFy4",
          "duration": "3s"
        }, {
          "placeId": "ChIJN5SqgQUOxYkRmRYOoyUMzYc",
          "duration": "4s"
        }, {
          "placeId": "ChIJK9cFiAUOxYkRxPoDhLRYqNY",
          "duration": "1s"
        }, {
          "placeId": "ChIJteD1YA8OxYkR_N5ieHx65jU",
          "duration": "3s"
        }, {
          "placeId": "ChIJc_lEWg8OxYkRUcVGDnXtOSU",
          "duration": "2s"
        }, {
          "placeId": "ChIJhQ5dUA8OxYkR0LUde4vr3vg",
          "duration": "2s"
        }, {
          "placeId": "ChIJt5yiTQ8OxYkRfXgeSAQ8cqo",
          "duration": "3s"
        }, {
          "placeId": "ChIJUSxGuAgOxYkRX9Bus6_kOw4",
          "duration": "8s"
        }, {
          "placeId": "ChIJif40-AgOxYkRlJWmsGQqgrE",
          "duration": "16s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkR0FS2zl6uWjU",
          "duration": "13s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkRkdxcop9FuuM",
          "duration": "3s"
        }, {
          "placeId": "ChIJE0xG0AkOxYkRVwGM6K1GcuA",
          "duration": "4s"
        }, {
          "placeId": "ChIJGXUibeINxYkRLx8FgZubHW4",
          "duration": "4s"
        }, {
          "placeId": "ChIJ08GYOeINxYkRgCf0e-0CjP0",
          "duration": "14s"
        }, {
          "placeId": "ChIJ08GYOeINxYkR113RzCdS3GM",
          "duration": "3s"
        }, {
          "placeId": "ChIJIR9oyeMNxYkR7YZiEcFz4XU",
          "duration": "6s"
        }, {
          "placeId": "ChIJURUPweMNxYkRenviPaiT_-I",
          "duration": "7s"
        }, {
          "placeId": "ChIJOar_7eMNxYkRiVffs-TSDCk",
          "duration": "7s"
        }, {
          "placeId": "ChIJ0WpbCOQNxYkR47_z_pTJqY8",
          "duration": "6s"
        }, {
          "placeId": "ChIJmXX9I-QNxYkR5kI-BtH4F78",
          "duration": "20s"
        }, {
          "placeId": "ChIJg5vt1eUNxYkRwlgL4wuJc9s",
          "duration": "1s"
        }, {
          "placeId": "ChIJPY8H1uUNxYkRUGXvuA0X2ZE",
          "duration": "2s"
        }, {
          "placeId": "ChIJfzzg0OUNxYkRWJEBhRho7u8",
          "duration": "10s"
        }, {
          "placeId": "ChIJ0QjnxuUNxYkRjWqhXpbR9w0",
          "duration": "8s"
        }, {
          "placeId": "ChIJV46eleUNxYkRTaCMUVovmXM",
          "duration": "7s"
        }, {
          "placeId": "ChIJq8TxkeUNxYkRjrMedy2oj_s",
          "duration": "4s"
        }, {
          "placeId": "ChIJI6PfjuUNxYkRmSjgtpYSqRs",
          "duration": "4s"
        }, {
          "placeId": "ChIJr9oxYe8NxYkRAflQvvqA4i8",
          "duration": "10s"
        }, {
          "placeId": "ChIJR8sj1O4NxYkR4ushCYmV9Z0",
          "duration": "42s"
        }, {
          "placeId": "ChIJr3BxVekNxYkR2vMxfQzkBug",
          "duration": "9s"
        }, {
          "placeId": "ChIJD0qnLJMNxYkRw40eRB765-4",
          "duration": "8s"
        }, {
          "placeId": "ChIJaV451pINxYkRLcvK9HtPt2g",
          "duration": "4s"
        }, {
          "placeId": "ChIJna-Q2pINxYkRjdtDMmTzxTI",
          "duration": "8s"
        }],
        "distanceMeters": 22886.71584749255,
        "travelMode": "DRIVE",
        "confidence": 0.973985468404679
      },
      "simplifiedRawPath": {
        "points": [{
          "latE7": 412358131,
          "lngE7": -758494110,
          "accuracyMeters": 5,
          "timestamp": "2022-05-01T17:35:06.503Z"
        }]
      },
      "parkingEvent": {
        "location": {
          "latitudeE7": 412106958,
          "longitudeE7": -760169276,
          "accuracyMetres": 65
        },
        "method": "END_OF_ACTIVITY_SEGMENT",
        "locationSource": "FROM_RAW_LOCATION",
        "timestamp": "2022-05-01T17:48:21.396Z"
      }
    }
  }, {
    "placeVisit": {
      "location": {
        "latitudeE7": 412106935,
        "longitudeE7": -760172268,
        "placeId": "ChIJZ70rw5INxYkR1cYKO_liHCo",
        "address": "14 Rock St, Nanticoke, PA 18634, USA",
        "semanticType": "TYPE_SEARCHED_ADDRESS",
        "sourceInfo": {
          "deviceTag": -1449989162
        },
        "locationConfidence": 65.21126,
        "calibratedProbability": 35.636124
      },
      "duration": {
        "startTimestamp": "2022-05-01T17:48:05.916Z",
        "endTimestamp": "2022-05-01T20:39:24.432Z"
      },
      "placeConfidence": "HIGH_CONFIDENCE",
      "centerLatE7": 412107290,
      "centerLngE7": -760170238,
      "visitConfidence": 75,
      "otherCandidateLocations": [{
        "latitudeE7": 412121388,
        "longitudeE7": -760185751,
        "placeId": "ChIJ906kxJINxYkRWRBx6PghBG0",
        "address": "101 Honey Pot St, Nanticoke, PA 18634, USA",
        "semanticType": "TYPE_HOME",
        "locationConfidence": 17.885334,
        "calibratedProbability": 9.773832
      }, {
        "latitudeE7": 412105829,
        "longitudeE7": -760169547,
        "placeId": "ChIJZdo-25INxYkRmuKwSR7ZfMc",
        "address": "99 Garfield St, Nanticoke, PA 18634, USA",
        "semanticType": "TYPE_SEARCHED_ADDRESS",
        "locationConfidence": 11.788492,
        "calibratedProbability": 6.44208
      }, {
        "latitudeE7": 412117488,
        "longitudeE7": -760152012,
        "placeId": "ChIJET2XWu0NxYkRF8v4Dwl6pjA",
        "address": "Nanticoke, PA 18634, USA",
        "name": "Honey Pot",
        "locationConfidence": 0.5603087,
        "calibratedProbability": 0.30619296
      }, {
        "latitudeE7": 412110083,
        "longitudeE7": -760170655,
        "placeId": "ChIJ1YX_wJINxYkRJmt8enZL8bc",
        "address": "11 Garfield St, Nanticoke, PA 18634, USA",
        "name": "Delta Electrical Systems Inc",
        "locationConfidence": 0.39598382,
        "calibratedProbability": 0.21639404
      }],
      "editConfirmationStatus": "NOT_CONFIRMED",
      "locationConfidence": 52,
      "placeVisitType": "SINGLE_PLACE",
      "placeVisitImportance": "MAIN"
    }
  }, {
    "activitySegment": {
      "startLocation": {
        "latitudeE7": 412104681,
        "longitudeE7": -760167060,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "endLocation": {
        "latitudeE7": 412124635,
        "longitudeE7": -758984771,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "duration": {
        "startTimestamp": "2022-05-01T20:39:24.432Z",
        "endTimestamp": "2022-05-01T20:50:36.544Z"
      },
      "distance": 10822,
      "activityType": "IN_PASSENGER_VEHICLE",
      "confidence": "HIGH",
      "activities": [{
        "activityType": "IN_PASSENGER_VEHICLE",
        "probability": 97.67943620681763
      }, {
        "activityType": "STILL",
        "probability": 0.9401029907166958
      }, {
        "activityType": "WALKING",
        "probability": 0.7795569021254778
      }, {
        "activityType": "MOTORCYCLING",
        "probability": 0.3215908771380782
      }, {
        "activityType": "CYCLING",
        "probability": 0.12136761797592044
      }, {
        "activityType": "IN_BUS",
        "probability": 0.04440594057086855
      }, {
        "activityType": "RUNNING",
        "probability": 0.04038455954287201
      }, {
        "activityType": "IN_FERRY",
        "probability": 0.0398215459426865
      }, {
        "activityType": "FLYING",
        "probability": 0.010878034663619474
      }, {
        "activityType": "SKIING",
        "probability": 0.009308080916525796
      }, {
        "activityType": "IN_TRAIN",
        "probability": 0.008483474812237546
      }, {
        "activityType": "SAILING",
        "probability": 0.0030376248105312698
      }, {
        "activityType": "IN_SUBWAY",
        "probability": 0.0014533035027852748
      }, {
        "activityType": "IN_TRAM",
        "probability": 1.605164811735449E-4
      }, {
        "activityType": "IN_VEHICLE",
        "probability": 1.7241795768896395E-7
      }],
      "waypointPath": {
        "waypoints": [{
          "latE7": 412104797,
          "lngE7": -760166702
        }, {
          "latE7": 412015991,
          "lngE7": -759162826
        }, {
          "latE7": 412124633,
          "lngE7": -758984832
        }],
        "source": "INFERRED",
        "roadSegment": [{
          "placeId": "ChIJna-Q2pINxYkRjNtDMmTzxTI",
          "duration": "3s"
        }, {
          "placeId": "ChIJaV451pINxYkRLMvK9HtPt2g",
          "duration": "4s"
        }, {
          "placeId": "ChIJD0qnLJMNxYkRwo0eRB765-4",
          "duration": "6s"
        }, {
          "placeId": "ChIJr3BxVekNxYkR2_MxfQzkBug",
          "duration": "7s"
        }, {
          "placeId": "ChIJR8sj1O4NxYkR4-shCYmV9Z0",
          "duration": "31s"
        }, {
          "placeId": "ChIJr9oxYe8NxYkRAPlQvvqA4i8",
          "duration": "10s"
        }, {
          "placeId": "ChIJI6PfjuUNxYkRmCjgtpYSqRs",
          "duration": "2s"
        }, {
          "placeId": "ChIJq8TxkeUNxYkRj7Medy2oj_s",
          "duration": "2s"
        }, {
          "placeId": "ChIJV46eleUNxYkRTKCMUVovmXM",
          "duration": "5s"
        }, {
          "placeId": "ChIJ0QjnxuUNxYkRjGqhXpbR9w0",
          "duration": "7s"
        }, {
          "placeId": "ChIJfzzg0OUNxYkRWZEBhRho7u8",
          "duration": "12s"
        }, {
          "placeId": "ChIJPY8H1uUNxYkRUWXvuA0X2ZE",
          "duration": "3s"
        }, {
          "placeId": "ChIJg5vt1eUNxYkRw1gL4wuJc9s",
          "duration": "0s"
        }, {
          "placeId": "ChIJmXX9I-QNxYkR50I-BtH4F78",
          "duration": "16s"
        }, {
          "placeId": "ChIJ0WpbCOQNxYkR4r_z_pTJqY8",
          "duration": "3s"
        }, {
          "placeId": "ChIJOar_7eMNxYkRiFffs-TSDCk",
          "duration": "5s"
        }, {
          "placeId": "ChIJURUPweMNxYkRe3viPaiT_-I",
          "duration": "5s"
        }, {
          "placeId": "ChIJIR9oyeMNxYkR7IZiEcFz4XU",
          "duration": "4s"
        }, {
          "placeId": "ChIJ08GYOeINxYkR1l3RzCdS3GM",
          "duration": "2s"
        }, {
          "placeId": "ChIJ08GYOeINxYkRgSf0e-0CjP0",
          "duration": "13s"
        }, {
          "placeId": "ChIJGXUibeINxYkRLh8FgZubHW4",
          "duration": "3s"
        }, {
          "placeId": "ChIJE0xG0AkOxYkRVgGM6K1GcuA",
          "duration": "2s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkRkNxcop9FuuM",
          "duration": "2s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkR0VS2zl6uWjU",
          "duration": "9s"
        }, {
          "placeId": "ChIJif40-AgOxYkRlZWmsGQqgrE",
          "duration": "12s"
        }, {
          "placeId": "ChIJUSxGuAgOxYkRXtBus6_kOw4",
          "duration": "5s"
        }, {
          "placeId": "ChIJt5yiTQ8OxYkRPrsi0Dx0h7U",
          "duration": "1s"
        }, {
          "placeId": "ChIJhQ5dUA8OxYkRu6YjZCrrwb4",
          "duration": "1s"
        }, {
          "placeId": "ChIJ9SEHWw8OxYkRt0BL7dbctV8",
          "duration": "0s"
        }, {
          "placeId": "ChIJeUOWfA8OxYkRk-_efkESy-A",
          "duration": "1s"
        }, {
          "placeId": "ChIJeUOWfA8OxYkRzJSAEmVcK84",
          "duration": "7s"
        }, {
          "placeId": "ChIJ_52lAxEOxYkRqXm17zCxQtU",
          "duration": "1s"
        }, {
          "placeId": "ChIJ0ebRED4OxYkR3Zxpfvyfq-E",
          "duration": "1s"
        }, {
          "placeId": "ChIJf-C4aT4OxYkRSETaUPpYIUE",
          "duration": "3s"
        }, {
          "placeId": "ChIJ3bwl8j4OxYkRNwBhGgk_d38",
          "duration": "5s"
        }, {
          "placeId": "ChIJW9BT6T4OxYkRRnpkw4JEqsc",
          "duration": "1s"
        }, {
          "placeId": "ChIJOX1kJzoOxYkRf5VcklPnKuk",
          "duration": "30s"
        }, {
          "placeId": "ChIJAcMNDDEOxYkRGLUljJGDppw",
          "duration": "3s"
        }, {
          "placeId": "ChIJpzaRhjEOxYkRHaKhWup2KdU",
          "duration": "3s"
        }, {
          "placeId": "ChIJBXTXgc0PxYkRxwROnduVTtw",
          "duration": "3s"
        }, {
          "placeId": "ChIJBXTXgc0PxYkRaC57tTeyKVQ",
          "duration": "6s"
        }, {
          "placeId": "ChIJw_E0LMMPxYkRYjc7ENLLQm4",
          "duration": "6s"
        }, {
          "placeId": "ChIJTZaqyMIPxYkR5n44QpCiT8w",
          "duration": "0s"
        }, {
          "placeId": "ChIJj2r2ROgPxYkRwB-RErYNFeE",
          "duration": "3s"
        }, {
          "placeId": "ChIJj2r2ROgPxYkR3KcdK56HhGw",
          "duration": "4s"
        }, {
          "placeId": "ChIJB72HROgPxYkR3pUnjj2RtTE",
          "duration": "2s"
        }, {
          "placeId": "ChIJRzxOiOgPxYkRJaOyUAHEP8g",
          "duration": "4s"
        }, {
          "placeId": "ChIJRzxOiOgPxYkRXwks3J8JKXg",
          "duration": "0s"
        }, {
          "placeId": "ChIJ41O1negPxYkRi-YEGzrDeE8",
          "duration": "6s"
        }, {
          "placeId": "ChIJP1ZOIOYPxYkRuIvoI5GcVik",
          "duration": "0s"
        }, {
          "placeId": "ChIJ9SphH-YPxYkRJuUywYC7pak",
          "duration": "0s"
        }, {
          "placeId": "ChIJu44YH-YPxYkRdwCkMzIlqp8",
          "duration": "0s"
        }, {
          "placeId": "ChIJDz4_GeYPxYkRUqE4Y1--jR8",
          "duration": "1s"
        }, {
          "placeId": "ChIJX1_NG-YPxYkRkLO50SF0nqo",
          "duration": "0s"
        }, {
          "placeId": "ChIJ_SR6CeYPxYkR4kfK2Zy2W8A",
          "duration": "10s"
        }, {
          "placeId": "ChIJ9zQOxOUPxYkRfq5kCW0JoeU",
          "duration": "4s"
        }, {
          "placeId": "ChIJtUE7_-QPxYkRjmrVr9z4xN4",
          "duration": "15s"
        }, {
          "placeId": "ChIJI4vCrOQPxYkRbaaoyrB7pP0",
          "duration": "14s"
        }, {
          "placeId": "ChIJTc9zvfwPxYkRoy5F7YODmAU",
          "duration": "3s"
        }, {
          "placeId": "ChIJa48w7fwPxYkR2BMfpJh1PAo",
          "duration": "4s"
        }, {
          "placeId": "ChIJ407Y9vwPxYkRBCRT0CtyF-o",
          "duration": "1s"
        }, {
          "placeId": "ChIJf2GhU_wPxYkRbwv0QHVxzns",
          "duration": "7s"
        }, {
          "placeId": "ChIJ0VjCx_0PxYkRpALr_fF_YdM",
          "duration": "6s"
        }, {
          "placeId": "ChIJ3RSe5_0PxYkRTGx9a44HkBA",
          "duration": "4s"
        }, {
          "placeId": "ChIJ41WJ4v0PxYkRPRSLOyOs8RA",
          "duration": "1s"
        }, {
          "placeId": "ChIJ1bvwBv4PxYkRibSowP3wy9E",
          "duration": "1s"
        }, {
          "placeId": "ChIJzyRN_QEQxYkRJPWJMPB6ZgU",
          "duration": "5s"
        }, {
          "placeId": "ChIJefkW6AEQxYkRkcEs8ibqUM0",
          "duration": "4s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRKqqacfbA6Uc",
          "duration": "8s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRYqS4-na-zBM",
          "duration": "5s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkRWclki4fv0Wg",
          "duration": "1s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkROjjV5Qnr3tM",
          "duration": "6s"
        }, {
          "placeId": "ChIJQ2wclQAQxYkR0M-b3liYOwQ",
          "duration": "0s"
        }, {
          "placeId": "ChIJVyESvgAQxYkRITvYT4Uw8qg",
          "duration": "3s"
        }, {
          "placeId": "ChIJGaZquwAQxYkRAPL00k-vffA",
          "duration": "5s"
        }, {
          "placeId": "ChIJ63u1nwAQxYkRpkYvMcKfaZU",
          "duration": "19s"
        }, {
          "placeId": "ChIJVYsde6oaxYkRV9LeTwnol58",
          "duration": "3s"
        }, {
          "placeId": "ChIJi7lkbqoaxYkRWDbhAlkqTyM",
          "duration": "9s"
        }, {
          "placeId": "ChIJB3XYKaoaxYkR-1tMR7kSNiU",
          "duration": "23s"
        }],
        "distanceMeters": 11707.176847931121,
        "travelMode": "DRIVE",
        "confidence": 0.9999422136108582
      },
      "parkingEvent": {
        "location": {
          "latitudeE7": 412129925,
          "longitudeE7": -758980088,
          "accuracyMetres": 79
        },
        "method": "END_OF_ACTIVITY_SEGMENT",
        "locationSource": "NOT_FROM_RAW_LOCATION",
        "timestamp": "2022-05-01T20:51:39.570Z"
      }
    }
  }, {
    "placeVisit": {
      "location": {
        "latitudeE7": 412112007,
        "longitudeE7": -758984985,
        "placeId": "ChIJB4B_VTEbxYkRlrZWUAj6vtg",
        "address": "Hazleton St, Ashley, PA 18706, USA",
        "name": "Ashley Trailer Park",
        "sourceInfo": {
          "deviceTag": -1449989162
        },
        "locationConfidence": 63.2388,
        "calibratedProbability": 47.793808
      },
      "duration": {
        "startTimestamp": "2022-05-01T20:50:36.544Z",
        "endTimestamp": "2022-05-01T20:57:02.049Z"
      },
      "placeConfidence": "MEDIUM_CONFIDENCE",
      "centerLatE7": 412127800,
      "centerLngE7": -758981333,
      "visitConfidence": 89,
      "otherCandidateLocations": [{
        "latitudeE7": 412139010,
        "longitudeE7": -758998260,
        "placeId": "ChIJn6d14akaxYkRHLRmDMln3ro",
        "address": "1 N Main St, Ashley, PA 18706, USA",
        "name": "Kelsey�u0027s",
        "locationConfidence": 8.851052,
        "calibratedProbability": 6.689335
      }, {
        "latitudeE7": 412128970,
        "longitudeE7": -758979000,
        "placeId": "ChIJy1E9j6kaxYkRJTNBNWpOg9U",
        "address": "86 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 6.353684,
        "calibratedProbability": 4.8019056
      }, {
        "latitudeE7": 412128943,
        "longitudeE7": -758978353,
        "placeId": "ChIJ9ZEkc6kaxYkRJydgLHIpVNg",
        "address": "67 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 5.677438,
        "calibratedProbability": 4.290821
      }, {
        "latitudeE7": 412127898,
        "longitudeE7": -758979345,
        "placeId": "ChIJ4xM6iakaxYkRQdCa2g9YpCU",
        "address": "61 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 3.111912,
        "calibratedProbability": 2.351881
      }, {
        "latitudeE7": 412115157,
        "longitudeE7": -759015916,
        "placeId": "ChIJ6e156wAQxYkRXGkL2RgbhZs",
        "address": "43 S Main St, Ashley, PA 18706, USA",
        "name": "Family Dollar",
        "locationConfidence": 2.7163017,
        "calibratedProbability": 2.0528917
      }, {
        "latitudeE7": 412121196,
        "longitudeE7": -759001558,
        "placeId": "ChIJBUMUpgAQxYkRf4cYPsxGcDE",
        "address": "1 Hazleton St, Ashley, PA 18706, USA",
        "name": "Ashley Municipal Park",
        "locationConfidence": 1.9144554,
        "calibratedProbability": 1.4468826
      }, {
        "latitudeE7": 412125577,
        "longitudeE7": -758986315,
        "placeId": "ChIJc9AxHqoaxYkRGOfpddkkY20",
        "address": "50 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 1.3010298,
        "calibratedProbability": 0.98327565
      }, {
        "latitudeE7": 412129741,
        "longitudeE7": -758977438,
        "placeId": "ChIJi7-cj6kaxYkRty7fSoPz_hk",
        "address": "87 Andrew Dr, Ashley, PA 18706, USA",
        "locationConfidence": 1.1719191,
        "calibratedProbability": 0.885698
      }, {
        "latitudeE7": 412145068,
        "longitudeE7": -758994817,
        "placeId": "ChIJJXFaFSAbxYkRZ01zIyl39wc",
        "address": "23 N Main St, Ashley, PA 18706, USA",
        "name": "The Grand Bank",
        "locationConfidence": 1.0543221,
        "calibratedProbability": 0.7968221
      }],
      "editConfirmationStatus": "NOT_CONFIRMED",
      "locationConfidence": 51,
      "placeVisitType": "SINGLE_PLACE",
      "placeVisitImportance": "MAIN"
    }
  }, {
    "activitySegment": {
      "startLocation": {
        "latitudeE7": 412109098,
        "longitudeE7": -758995723,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "endLocation": {
        "latitudeE7": 412107581,
        "longitudeE7": -760169482,
        "sourceInfo": {
          "deviceTag": -1449989162
        }
      },
      "duration": {
        "startTimestamp": "2022-05-01T20:57:02.049Z",
        "endTimestamp": "2022-05-01T21:08:07.127Z"
      },
      "distance": 10584,
      "activityType": "IN_PASSENGER_VEHICLE",
      "confidence": "HIGH",
      "activities": [{
        "activityType": "IN_PASSENGER_VEHICLE",
        "probability": 97.61692881584167
      }, {
        "activityType": "WALKING",
        "probability": 0.8737282827496529
      }, {
        "activityType": "STILL",
        "probability": 0.6910582538694143
      }, {
        "activityType": "MOTORCYCLING",
        "probability": 0.5351859144866467
      }, {
        "activityType": "CYCLING",
        "probability": 0.1529011526145041
      }, {
        "activityType": "RUNNING",
        "probability": 0.03970175457652658
      }, {
        "activityType": "IN_BUS",
        "probability": 0.03851574438158423
      }, {
        "activityType": "IN_FERRY",
        "probability": 0.026751408586278558
      }, {
        "activityType": "FLYING",
        "probability": 0.009733462502481416
      }, {
        "activityType": "SKIING",
        "probability": 0.008502759010298178
      }, {
        "activityType": "IN_TRAIN",
        "probability": 0.003941653994843364
      }, {
        "activityType": "SAILING",
        "probability": 0.0022478441678686067
      }, {
        "activityType": "IN_SUBWAY",
        "probability": 7.431376616295893E-4
      }, {
        "activityType": "IN_TRAM",
        "probability": 5.703942065338197E-5
      }, {
        "activityType": "IN_VEHICLE",
        "probability": 4.955700849684774E-8
      }],
      "waypointPath": {
        "waypoints": [{
          "latE7": 412109107,
          "lngE7": -758995742
        }, {
          "latE7": 412057266,
          "lngE7": -759089050
        }, {
          "latE7": 412107887,
          "lngE7": -760168533
        }],
        "source": "INFERRED",
        "roadSegment": [{
          "placeId": "ChIJ63u1nwAQxYkRp0YvMcKfaZU",
          "duration": "18s"
        }, {
          "placeId": "ChIJGaZquwAQxYkRAfL00k-vffA",
          "duration": "4s"
        }, {
          "placeId": "ChIJVyESvgAQxYkRIDvYT4Uw8qg",
          "duration": "3s"
        }, {
          "placeId": "ChIJQ2wclQAQxYkR0c-b3liYOwQ",
          "duration": "0s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkROzjV5Qnr3tM",
          "duration": "6s"
        }, {
          "placeId": "ChIJ-YsA7gAQxYkRWMlki4fv0Wg",
          "duration": "2s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRY6S4-na-zBM",
          "duration": "5s"
        }, {
          "placeId": "ChIJaa90sgEQxYkRK6qacfbA6Uc",
          "duration": "8s"
        }, {
          "placeId": "ChIJefkW6AEQxYkRkMEs8ibqUM0",
          "duration": "4s"
        }, {
          "placeId": "ChIJzyRN_QEQxYkRJfWJMPB6ZgU",
          "duration": "5s"
        }, {
          "placeId": "ChIJ1bvwBv4PxYkRiLSowP3wy9E",
          "duration": "1s"
        }, {
          "placeId": "ChIJ41WJ4v0PxYkRPBSLOyOs8RA",
          "duration": "1s"
        }, {
          "placeId": "ChIJ3RSe5_0PxYkRTWx9a44HkBA",
          "duration": "3s"
        }, {
          "placeId": "ChIJ0VjCx_0PxYkRpQLr_fF_YdM",
          "duration": "5s"
        }, {
          "placeId": "ChIJf2GhU_wPxYkRbgv0QHVxzns",
          "duration": "7s"
        }, {
          "placeId": "ChIJ407Y9vwPxYkRBSRT0CtyF-o",
          "duration": "1s"
        }, {
          "placeId": "ChIJa48w7fwPxYkR2RMfpJh1PAo",
          "duration": "4s"
        }, {
          "placeId": "ChIJTc9zvfwPxYkRoi5F7YODmAU",
          "duration": "3s"
        }, {
          "placeId": "ChIJI4vCrOQPxYkRbKaoyrB7pP0",
          "duration": "14s"
        }, {
          "placeId": "ChIJtUE7_-QPxYkRj2rVr9z4xN4",
          "duration": "16s"
        }, {
          "placeId": "ChIJ9zQOxOUPxYkRf65kCW0JoeU",
          "duration": "4s"
        }, {
          "placeId": "ChIJ_SR6CeYPxYkR40fK2Zy2W8A",
          "duration": "11s"
        }, {
          "placeId": "ChIJX1_NG-YPxYkRkbO50SF0nqo",
          "duration": "0s"
        }, {
          "placeId": "ChIJDz4_GeYPxYkRU6E4Y1--jR8",
          "duration": "1s"
        }, {
          "placeId": "ChIJu44YH-YPxYkRdgCkMzIlqp8",
          "duration": "0s"
        }, {
          "placeId": "ChIJu44YH-YPxYkR8_QV6TgMUgQ",
          "duration": "2s"
        }, {
          "placeId": "ChIJO1pQt8IPxYkRpdzI3YbJESc",
          "duration": "0s"
        }, {
          "placeId": "ChIJkab6zsIPxYkRNXz96xZxzcY",
          "duration": "2s"
        }, {
          "placeId": "ChIJx9B9LMMPxYkRQN7IlTe8Vgg",
          "duration": "2s"
        }, {
          "placeId": "ChIJx9B9LMMPxYkR3O_EPcfaiZs",
          "duration": "2s"
        }, {
          "placeId": "ChIJ8QtmgM0PxYkRZgDF6iZCHG4",
          "duration": "2s"
        }, {
          "placeId": "ChIJGcMYgM0PxYkRroCvZNsZYyU",
          "duration": "0s"
        }, {
          "placeId": "ChIJGcMYgM0PxYkR4Qqsicbw5IM",
          "duration": "7s"
        }, {
          "placeId": "ChIJwUfEPTIOxYkRUkuChCArEtM",
          "duration": "1s"
        }, {
          "placeId": "ChIJOyamnDEOxYkRuUPgF0PVGRM",
          "duration": "9s"
        }, {
          "placeId": "ChIJOyamnDEOxYkR7fKr8ri1CmE",
          "duration": "1s"
        }, {
          "placeId": "ChIJlTcaBDoOxYkRFb2LAB8AFWI",
          "duration": "3s"
        }, {
          "placeId": "ChIJvWAHHjoOxYkRJsJDsJwmCLc",
          "duration": "10s"
        }, {
          "placeId": "ChIJvWAHHjoOxYkRvnDC3akm-Yg",
          "duration": "4s"
        }, {
          "placeId": "ChIJWYUSODkOxYkRO6N5kqHmwMg",
          "duration": "8s"
        }, {
          "placeId": "ChIJWYUSODkOxYkR5owZh_xhcDI",
          "duration": "5s"
        }, {
          "placeId": "ChIJZyxl7D4OxYkRfAhSRROU7nc",
          "duration": "1s"
        }, {
          "placeId": "ChIJLZlAaT4OxYkR89FFc05HI_A",
          "duration": "9s"
        }, {
          "placeId": "ChIJQ9opNxEOxYkRPVPRd9mUgQE",
          "duration": "1s"
        }, {
          "placeId": "ChIJ8-Gz8hAOxYkRlGndomOBgi0",
          "duration": "20s"
        }, {
          "placeId": "ChIJz1g2ihoOxYkREExuMpsF8yM",
          "duration": "9s"
        }, {
          "placeId": "ChIJ5Zar9RoOxYkRLTaHv2AVEJk",
          "duration": "0s"
        }, {
          "placeId": "ChIJIaCH9BoOxYkRJwcKgFcKOc4",
          "duration": "0s"
        }, {
          "placeId": "ChIJjfBB7RoOxYkRu1OXXozNuVY",
          "duration": "2s"
        }, {
          "placeId": "ChIJhwcKuRoOxYkRO6S7HsLqQOU",
          "duration": "7s"
        }, {
          "placeId": "ChIJhwcKuRoOxYkRDhe_JPgFVxc",
          "duration": "0s"
        }, {
          "placeId": "ChIJfRkyRQUOxYkR4Nmaxpbz5IY",
          "duration": "6s"
        }, {
          "placeId": "ChIJd6_sZAUOxYkRAiDsN0pRFy4",
          "duration": "2s"
        }, {
          "placeId": "ChIJN5SqgQUOxYkRmRYOoyUMzYc",
          "duration": "3s"
        }, {
          "placeId": "ChIJK9cFiAUOxYkRxPoDhLRYqNY",
          "duration": "0s"
        }, {
          "placeId": "ChIJteD1YA8OxYkR_N5ieHx65jU",
          "duration": "2s"
        }, {
          "placeId": "ChIJc_lEWg8OxYkRUcVGDnXtOSU",
          "duration": "1s"
        }, {
          "placeId": "ChIJhQ5dUA8OxYkR0LUde4vr3vg",
          "duration": "1s"
        }, {
          "placeId": "ChIJt5yiTQ8OxYkRfXgeSAQ8cqo",
          "duration": "2s"
        }, {
          "placeId": "ChIJUSxGuAgOxYkRX9Bus6_kOw4",
          "duration": "6s"
        }, {
          "placeId": "ChIJif40-AgOxYkRlJWmsGQqgrE",
          "duration": "13s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkR0FS2zl6uWjU",
          "duration": "10s"
        }, {
          "placeId": "ChIJEdBIzgkOxYkRkdxcop9FuuM",
          "duration": "2s"
        }, {
          "placeId": "ChIJE0xG0AkOxYkRVwGM6K1GcuA",
          "duration": "3s"
        }, {
          "placeId": "ChIJGXUibeINxYkRLx8FgZubHW4",
          "duration": "3s"
        }, {
          "placeId": "ChIJ08GYOeINxYkRgCf0e-0CjP0",
          "duration": "11s"
